process.env.IPAPI_URL="http://ip-api.com/json/"
process.env.WEATHER_SERVICE="WeatherAPI"
process.env.WEATHER_SERVICE_URL_CURRENT="http://api.weatherapi.com/v1/current.json"
process.env.WEATHER_SERVICE_URL_FORECAST="http://api.weatherapi.com/v1/forecast.json"
process.env.WEATHER_SERVICE_KEY="400dc45c04b84db9936185138221705"